export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{ 
      margin: 0,
      padding: 0,
      background: 'linear-gradient(to bottom, #0a0a0a, #1a1a1a, #0a0a0a)',
      minHeight: '100vh'
    }}>
      <body style={{ 
        margin: 0,
        padding: 0,
        minHeight: '100vh',
        background: 'linear-gradient(to bottom, #0a0a0a, #1a1a1a, #0a0a0a)'
      }}>
        {children}
      </body>
    </html>
  )
}
